name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-*
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, stage, prod]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade --force-reinstall pip setuptools wheel  # Install setuptools and wheel to include distutils
  
  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python test.py

   # - name: Build and Push Docker Image
    #  run: |
    #    docker build -t your-docker-username/house-price-prediction:${{ matrix.environment }} .
    #    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #    docker push your-docker-username/house-price-prediction:${{ matrix.environment }}
      

    - name: Deploy to Vercel
      if: ${{ matrix.environment == 'prod' }}
      run: |
        npm install -g vercel
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
